/**
 * Daily Site Report PDF — uses the shared pdf-renderer primitives.
 */

import React from 'react';
import { Document, Text, View } from '@react-pdf/renderer';
import {
  COLOURS,
  PdfBadge,
  PdfKV,
  PdfPage,
  PdfSection,
  renderToBuffer,
} from './pdf-renderer';

export interface DailyReportPdfData {
  report: {
    report_date: string;
    weather_summary: string | null;
    weather_data: { temp_c?: number | null; humidity?: number | null; wind_mph?: number | null; description?: string; source?: string } | null;
    workforce_count: number | null;
    activities: string | null;
    plant_on_site: string | null;
    delays: string | null;
    safety_observations: string | null;
    visitors: string | null;
    notes: string | null;
    status: string;
  };
  projectName: string;
  generatedAt: string;
  generatedBy: string;
}

function DailyReportDocument({ data }: { data: DailyReportPdfData }) {
  const { report } = data;

  return (
    <Document title={`Daily Report — ${report.report_date}`} author="RAMS Compliance Review">
      <PdfPage docTitle="Daily Site Report" generatedAt={data.generatedAt}>
        {/* Header */}
        <View style={{ marginBottom: 16 }}>
          <Text style={{ fontSize: 16, fontWeight: 'bold', marginBottom: 4 }}>
            Daily Site Report
          </Text>
          <View style={{ flexDirection: 'row', gap: 6, marginBottom: 8 }}>
            <PdfBadge status={report.status} />
          </View>
          <PdfKV label="Project" value={data.projectName} />
          <PdfKV label="Date" value={report.report_date} />
          <PdfKV label="Generated by" value={data.generatedBy} />
        </View>

        {/* Weather */}
        {(report.weather_summary || report.weather_data) && (
          <PdfSection title="Weather Conditions">
            <View style={{ padding: 8, backgroundColor: COLOURS.bg, borderRadius: 4 }}>
              {report.weather_summary && (
                <Text style={{ fontSize: 10, fontWeight: 'bold', marginBottom: 4 }}>
                  {report.weather_summary}
                </Text>
              )}
              {report.weather_data && (
                <View style={{ flexDirection: 'row', gap: 16, marginTop: 2 }}>
                  {report.weather_data.temp_c != null && (
                    <Text style={{ fontSize: 8.5 }}>🌡 {report.weather_data.temp_c}°C</Text>
                  )}
                  {report.weather_data.humidity != null && (
                    <Text style={{ fontSize: 8.5 }}>💧 {report.weather_data.humidity}%</Text>
                  )}
                  {report.weather_data.wind_mph != null && (
                    <Text style={{ fontSize: 8.5 }}>💨 {report.weather_data.wind_mph} mph</Text>
                  )}
                  {report.weather_data.source && (
                    <Text style={{ fontSize: 7.5, color: COLOURS.muted }}>
                      Source: {report.weather_data.source === 'met_office' ? 'Met Office' : 'Manual'}
                    </Text>
                  )}
                </View>
              )}
            </View>
          </PdfSection>
        )}

        {/* Workforce */}
        {report.workforce_count != null && (
          <PdfSection title="Workforce">
            <Text style={{ fontSize: 22, fontWeight: 'bold', color: COLOURS.accent }}>
              {report.workforce_count}
            </Text>
            <Text style={{ fontSize: 8, color: COLOURS.muted }}>persons on site</Text>
          </PdfSection>
        )}

        {/* Activities */}
        {report.activities && (
          <PdfSection title="Activities">
            <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.activities}</Text>
          </PdfSection>
        )}

        {/* Plant on site */}
        {report.plant_on_site && (
          <PdfSection title="Plant & Equipment on Site">
            <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.plant_on_site}</Text>
          </PdfSection>
        )}

        {/* Delays */}
        {report.delays && (
          <PdfSection title="Delays / Issues">
            <View style={{ padding: 8, backgroundColor: '#fef9c3', borderRadius: 4 }}>
              <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.delays}</Text>
            </View>
          </PdfSection>
        )}

        {/* Safety observations */}
        {report.safety_observations && (
          <PdfSection title="Safety Observations">
            <View style={{ padding: 8, backgroundColor: '#fee2e2', borderRadius: 4 }}>
              <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.safety_observations}</Text>
            </View>
          </PdfSection>
        )}

        {/* Visitors */}
        {report.visitors && (
          <PdfSection title="Visitors">
            <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.visitors}</Text>
          </PdfSection>
        )}

        {/* Notes */}
        {report.notes && (
          <PdfSection title="Additional Notes">
            <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{report.notes}</Text>
          </PdfSection>
        )}
      </PdfPage>
    </Document>
  );
}

export async function generateDailyReportPdf(data: DailyReportPdfData): Promise<Buffer> {
  const buffer = await renderToBuffer(<DailyReportDocument data={data} />);
  return Buffer.from(buffer);
}
