/**
 * Incident Report PDF — RIDDOR-aligned format.
 *
 * Sections: Cover, Incident Details, Involved Parties, Related RAMS,
 * Attachments Manifest, Investigation / Corrective Actions.
 */

import React from 'react';
import { Document, Text, View } from '@react-pdf/renderer';
import {
  COLOURS,
  PdfBadge,
  PdfKV,
  PdfPage,
  PdfSection,
  PdfTable,
  renderToBuffer,
} from './pdf-renderer';

// ── Data types ────────────────────────────────────────────────────────────────

export interface IncidentParty {
  role: string;
  full_name: string;
  company: string | null;
  contact: string | null;
  notes: string | null;
}

export interface IncidentReportData {
  incident: {
    id: string;
    title: string;
    description: string | null;
    severity: string;
    status: string;
    occurred_at: string;
    location: string | null;
    riddor_reportable: boolean;
    riddor_reference: string | null;
    root_cause: string | null;
    corrective_actions: string | null;
    created_at: string;
  };
  parties: IncidentParty[];
  relatedRams: {
    subcontractor_name: string;
    file_name: string;
    review_status: string;
    compliance_score: number | null;
  } | null;
  projectName: string;
  attachmentCount: number;
  generatedAt: string;
  generatedBy: string;
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function fmtDate(iso: string): string {
  try {
    return new Date(iso).toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });
  } catch { return iso; }
}

function severityColour(s: string): string {
  const map: Record<string, string> = {
    fatality: COLOURS.danger,
    specified_injury: COLOURS.danger,
    dangerous_occurrence: COLOURS.danger,
    major: COLOURS.warning,
    minor: COLOURS.muted,
    near_miss: COLOURS.accent,
  };
  return map[s] ?? COLOURS.muted;
}

// ── Document ──────────────────────────────────────────────────────────────────

function IncidentReportDocument({ data }: { data: IncidentReportData }) {
  const { incident, parties, relatedRams } = data;

  return (
    <Document title={`Incident Report — ${incident.title}`} author="RAMS Compliance Review">
      <PdfPage docTitle="Incident Report" generatedAt={data.generatedAt}>

        {/* Cover block */}
        <View style={{
          borderWidth: 1, borderColor: COLOURS.border, borderRadius: 6,
          padding: 16, marginBottom: 16,
        }}>
          <Text style={{ fontSize: 16, fontWeight: 'bold', marginBottom: 8 }}>
            {incident.title}
          </Text>

          <View style={{ flexDirection: 'row', gap: 8, marginBottom: 10 }}>
            <PdfBadge status={incident.severity} />
            <PdfBadge status={incident.status} />
            {incident.riddor_reportable && <PdfBadge status="riddor_notified" />}
          </View>

          <PdfKV label="Project" value={data.projectName} />
          <PdfKV label="Date/Time" value={fmtDate(incident.occurred_at)} />
          <PdfKV label="Location" value={incident.location ?? '—'} />
          <PdfKV label="RIDDOR Reportable" value={incident.riddor_reportable ? 'Yes' : 'No'} />
          {incident.riddor_reference && (
            <PdfKV label="RIDDOR Reference" value={incident.riddor_reference} />
          )}
          <PdfKV label="Report Generated" value={data.generatedAt} />
          <PdfKV label="Generated By" value={data.generatedBy} />
        </View>

        {/* Description */}
        {incident.description && (
          <PdfSection title="Description">
            <Text style={{ fontSize: 9, lineHeight: 1.6 }}>{incident.description}</Text>
          </PdfSection>
        )}

        {/* Severity indicator */}
        <PdfSection title="Severity Classification">
          <View style={{
            flexDirection: 'row', alignItems: 'center', gap: 8,
            padding: 8, backgroundColor: COLOURS.bg, borderRadius: 4,
          }}>
            <View style={{
              width: 12, height: 12, borderRadius: 6,
              backgroundColor: severityColour(incident.severity),
            }} />
            <Text style={{ fontSize: 10, fontWeight: 'bold' }}>
              {incident.severity.replace(/_/g, ' ').toUpperCase()}
            </Text>
          </View>
        </PdfSection>

        {/* Involved parties */}
        {parties.length > 0 && (
          <PdfSection title={`Involved Parties (${parties.length})`}>
            <PdfTable
              columns={[
                { header: 'Role', width: 90, accessor: (r) => String((r as { role: string }).role).replace(/_/g, ' ') },
                { header: 'Name', width: 120, accessor: (r) => String((r as { full_name: string }).full_name) },
                { header: 'Company', width: 100, accessor: (r) => String((r as { company: string }).company || '—') },
                { header: 'Contact', width: 100, accessor: (r) => String((r as { contact: string }).contact || '—') },
                { header: 'Notes', width: 100, accessor: (r) => String((r as { notes: string }).notes || '—').slice(0, 80) },
              ]}
              rows={parties as unknown as Record<string, unknown>[]}
            />
          </PdfSection>
        )}

        {/* Related RAMS */}
        {relatedRams && (
          <PdfSection title="Related RAMS Submission">
            <View style={{
              padding: 8, backgroundColor: COLOURS.bg, borderRadius: 4,
              borderLeftWidth: 3, borderLeftColor: COLOURS.accent,
            }}>
              <PdfKV label="Subcontractor" value={relatedRams.subcontractor_name} />
              <PdfKV label="File" value={relatedRams.file_name} />
              <PdfKV label="Review Status" value={relatedRams.review_status.replace(/_/g, ' ')} />
              <PdfKV label="Compliance Score" value={
                relatedRams.compliance_score !== null ? `${relatedRams.compliance_score}%` : 'N/A'
              } />
            </View>
          </PdfSection>
        )}

        {/* Investigation */}
        {(incident.root_cause || incident.corrective_actions) && (
          <PdfSection title="Investigation">
            {incident.root_cause && (
              <View style={{ marginBottom: 8 }}>
                <Text style={{ fontSize: 8.5, fontWeight: 'bold', color: COLOURS.muted, marginBottom: 2 }}>Root Cause</Text>
                <Text style={{ fontSize: 9, lineHeight: 1.5 }}>{incident.root_cause}</Text>
              </View>
            )}
            {incident.corrective_actions && (
              <View>
                <Text style={{ fontSize: 8.5, fontWeight: 'bold', color: COLOURS.muted, marginBottom: 2 }}>Corrective Actions</Text>
                <Text style={{ fontSize: 9, lineHeight: 1.5 }}>{incident.corrective_actions}</Text>
              </View>
            )}
          </PdfSection>
        )}

        {/* Attachments summary */}
        {data.attachmentCount > 0 && (
          <PdfSection title="Attachments">
            <Text style={{ fontSize: 8.5, color: COLOURS.muted }}>
              {data.attachmentCount} file(s) attached to this incident report.
              See the online system for full access.
            </Text>
          </PdfSection>
        )}
      </PdfPage>
    </Document>
  );
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function generateIncidentReport(data: IncidentReportData): Promise<Buffer> {
  const buffer = await renderToBuffer(<IncidentReportDocument data={data} />);
  return Buffer.from(buffer);
}
